# -*- coding: utf-8 -*-
"""KMeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZzKBaH3ys0y6JAvPLd69hXDRxwE3BRGY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df= pd.DataFrame({'x':[0.1, 0.15,0.08,0.16,0.2,0.25,0.24,0.3],
                  'y':[0.6,0.71,0.9,0.85,0.3,0.5,0.1,0.2]})

f1= df['x'].values
f2= df['y'].values

x = np.array(list(zip(f1,f2)))

C_x = np.array([0.1,0.3])
C_y = np.array([0.6,0.2])

centroids = C_x, C_y

from sklearn.cluster import KMeans
model = KMeans(n_clusters=2, random_state = 0)
model.fit(x)
labels=model.labels_
print(labels)

count=0
for i in range(len(labels)):
  if labels[i]==1:
    count +=1
print("No. of population around cluster 2 is :", count)

new_centroid = model.cluster_centers_
print("Previous values of centroids are ")
print("M1==", centroids[0])
print("M2==", centroids[1])

print("Updated values of centroids are ")
print("M1==", new_centroid[0])
print("M2==", new_centroid[1])

