# -*- coding: utf-8 -*-
"""Matrx and vector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-UOJsfyX_fCwg-rePtltwzmI5yPM4M8
"""

# Vector matrix Multiplication
import random
import numpy as np
import time
M = 700
# Multiply Vector and matrix
A = np.random.randint(0, M, size=(M, M))
a = np.random.randint(0, M, size=M)
d = np.zeros(M, dtype=int)
# serial
start = time.time()
for i in range(M):
    sum = 0
    for j in range(M):
        sum += A[i][j] * a[j]
    d[i] = sum
duration = time.time() - start
print("Serial Multiply Vector and matrix:", duration)

# parallel
start = time.time()
d = np.dot(A, a)
duration = time.time() - start
print("Parallel Multiply Vector and matrix:", duration)



import random
import numpy as np
import time
# M = 700
# Multiply Vector and matrix
A = [[1,2,3],[1,2,3],[1,2,3]]
a = [1,2,3]
d = [0,0,0]
# serial
start = time.time()
for i in range(3):
    sum = 0
    for j in range(3):
        sum += A[i][j] * a[j]
    d[i] = sum
duration = time.time() - start
print("Serial Multiply Vector and matrix:", duration)

# parallel
start = time.time()
d = np.dot(A, a)
duration = time.time() - start
print("Parallel Multiply Vector and matrix:", duration)
print(d)

# Vector addition

import numpy as np
import random
import time

a=[2,4,5,6,7,8,9]
b=[1,2,3,2,3,4,5]
c=[0,0,0,0,0,0,0]
start = time.time()
for i in range(7):
    c[i]=a[i]+b[i]
duration = time.time() - start

print("serial time for vector addition" , duration)

start = time.time()
c=np.add(a,b)
duration = time.time() - start
print("parrale time for vector addition", duration)

# Matrix multiplication

import numpy as np
import time

A = np.random.randint(0, N, size=(N, N))
B = np.random.randint(0, N, size=(N, N))
C = np.zeros((N, N), dtype=int)

start = time.time()
for i in range(N):
  for j in range(N):
    c[i][j]=0
    for k in range(N):
      c[i][j] += a[i][k]*b[k][i]
duration  = time.time()- start
print("serial time for matrix multiplication : ", duration)

start =time.time()
c= np.dot(a,b)
duration = time.time()
print("parallel time for multiplication :",duration)