# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A450dOhdO_eb4dbvFQRquCw5AR6BfTUD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df= pd.read_csv('Iris.csv')

df

x= df.drop("Species", axis=1)

y= df['Species']

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x_scaled = scaler.fit_transform(x)

from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x_pca= pca.fit_transform(x_scaled)

explained_variance_ratio= pca.explained_variance_ratio_

print("Explained Variance Ratio ", explained_variance_ratio)

plt.scatter(x_pca[:,0],x_pca[:,1])
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA on Iris Dataset')
plt.show()

